### PR TITLE
PHPMD

### PR DESCRIPTION
**Pull request by osteel**

### CODE REVIEW

**Comment by smgladkovskiy** [comment]
Sorry, missed PR. Was it closed for further developing or what?

**Comment by osteel** [comment]
@smgladkovskiy nah mate, my bad, this was meant for my own fork!

**Comment by smgladkovskiy** [comment]
@osteel maybe it will be interesting and helpful for others? :)

**Comment by osteel** [comment]
@smgladkovskiy well I added [PHPMD](https://github.com/phpmd/phpmd) to your script, and also an environment variable to control whether the script should run the checks or not, and also an option to apply PHPCS' suggested changes automatically with PHPCBF (the ones that can be fixed automatically, anyway).

But I did all that a bit quickly. Ideally there should be an env var to enable/disable each check separately, on top of the env var controlling whether any check should be run at all. Also, My bash-fu isn't great.

But if you're interested in all of the above being merged to your repo, then I guess I can make a few PRs.

Although it'd also mean that the name of the repository (_php**cs**-git-pre-commit_) wouldn't be completely relevant anymore, as it wouldn't be just PHPCS anymore.

What do you think?

**Pull request closed without merging**
